openapi: 3.0.0
info:
  title: Gamenerd API
  description: De vetste gaming API beschikbaar
  version: 0.1.9

servers:
  - url: http://localhost:9000/api
    description: Je Locale instantie

paths:
  /games:
    get:
      summary: Returns a list of games.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of games
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: 
                    $ref: '#/components/schemas/GameOutputDto'
components:
  schemas:
    GameOutputDto:
      type: object
      properties:
        id:
          type: string
          example: 123
        name:
          type: string
          example: Skyrim
        boxart:
          type: string
          example: url to boxart
      required:
        - id
        - name
        - boxart